joinup:
  nacos:
    addr: ${NACOS_ADDR}
    namespace: ""
  rabbitmq:
    host: ${MQ_HOST}
    port: 5672
    virtual-host: /joinup-dev
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0