server:
  port: 8089

spring:
  application:
    name: websocket-service

  profiles:
    active: local

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
        namespace: ${joinup.nacos.namespace}

  rabbitmq:
    host: ${joinup.rabbitmq.host}
    port: ${joinup.rabbitmq.port}
    virtual-host: ${joinup.rabbitmq.virtual-host}
    username: ${joinup.rabbitmq.username}
    password: ${joinup.rabbitmq.password}