joinup:
  db:
    host: ${DB_HOST}
    port: 3306
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: file-service-prod
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  nacos:
    namespace: bcc1206a-17c8-401d-85a8-c7225a1a72b4
  aliyun:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: ${OSS_ACCESS_KEY_ID}
      accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
      bucketName: joinup